[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Sick AG"]

# The title and description fields are primarily for displaying extension info in UI
title = "modellink vac"
description="VAC stands for 'Virtual Automation Controller'."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["kit", "library", "ioc", "modellink", "vac"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[python.pipapi]
requirements = ['paho-mqtt']
use_online_index = true

# Use omni.ui to build simple UI
[dependencies]
"sick.modellink.core" = {}

# Main python module this extension provides, it will be publicly available as "import sick.modellink.samples".
[[python.module]]
name = "sick.modellink.vac"

